[#3] Feature(ChatRoom): 채팅방 기능
Recipe-GPT/server pull request #11
Opened 2023-05-25 11:38 UTC by min050410

### 수정 내용
- 채팅방 생성
- 채팅방 수정, 삭제
- 채팅방 조회

2023-05-25 13:30 UTC, leehj050211 requested changes

2023-05-25 13:30 UTC, leehj050211 commented on src/main/java/com/recipe/gpt/app/domain/chat/chatroom/ChatRoom.java
> +    public boolean isNotPossibleToAccessPlaylist(Member member) {
메서드 이름이 왜 이러죠?

2023-05-25 13:30 UTC, leehj050211 commented on src/main/java/com/recipe/gpt/app/domain/chat/chatroom/ChatRoom.java
> +    public boolean isNotPossibleToAccessChatRoom(Member member) {
저는 isNotPossibleToAccessChatRoom보단 !isAccessibleChatRoom이 더 읽기 쉽다고 생각하는데 영민 개발자님은 어떻게 생각하나요?
안에 코드도 한번 부정해서 생각해야 하니 쉽게 읽히진 않는 것 같네요.

2023-05-25 13:30 UTC, leehj050211 commented on src/main/java/com/recipe/gpt/app/domain/chat/chatroom/ChatRoomService.java
> +    public ListResponse<ChatRoomResponseDto> findChatRoomSelf(LoginMember loginMember) {
메서드 이름으로 findMyChatRoom은 어떤가요?

2023-05-25 16:59 UTC, min050410 commented on src/main/java/com/recipe/gpt/app/domain/chat/chatroom/ChatRoomService.java
> +    public ListResponse<ChatRoomResponseDto> findChatRoomSelf(LoginMember loginMember) {
좋네요

2023-05-25 17:38 UTC, min050410 commented on src/main/java/com/recipe/gpt/app/domain/chat/chatroom/ChatRoom.java
> +    public boolean isNotPossibleToAccessChatRoom(Member member) {
읽기 쉬운건 사람에 따라 다르긴 한데 밖에서 봤을 때 읽는 동안 단어별로 이해가되서 저는 개인적으로 전자입니다. 그래서 isNotPossibleToAccessChatRoom라는 내부 메서드를 생성한거기도 하구요.
```java
if (isNotPossibleToAccessChatRoom(member)) {
   // EXCEPTION
}
```
그런데 확장성 고려하니깐 고민이 되네요. Response Dto에 editable과 같은 필드를 만들 때 후자는 그대로 같다 쓸 수 있어 OCP에 더 맞는 메서드라는 생각이 듭니다. 후자로 수정해야겠습니다.

2023-05-26 13:49 UTC, min050410 commented
변경완료!

2023-05-26 14:00 UTC, leehj050211 approved these changes
👍

2023-05-29 23:16 UTC, merged