[#9] Feature(Api): 레시피 생성 API와 연결
Recipe-GPT/server pull request #13
Opened 2023-05-30 07:53 UTC by min050410

### 작업 내용
- 레시피 생성 API와 연결
- 문자열에서 재료의 양 추출 후 반환

2023-05-30 10:45 UTC, leehj050211 requested changes
코드 좋네요!

2023-05-30 10:45 UTC, leehj050211 commented on src/main/java/com/recipe/gpt/app/web/dto/recipe/ai/ItemResponseDto.java
> +            StringUtils.extractStringInsideParentheses(item)
이 부분은 혹시 나중에 AI의 답변이 변경되어서 소괄호말고 다른 부호를 사용할 수도 있어요.
그래도 지금은 변경할 예정이 없어서 굳이 바꿀 필요는 없을 것 같네요.

2023-05-30 10:45 UTC, leehj050211 commented on src/main/java/com/recipe/gpt/app/domain/chat/ChatService.java
> +        AiServerRecipeResponseDto response = webClient
recommendQuery 메서드하고 겹치는 코드가 많은 것 같은데 개선해보는건 어떨까요?

2023-06-01 23:23 UTC, leehj050211 requested changes

2023-06-01 23:23 UTC, leehj050211 commented on src/main/java/com/recipe/gpt/app/domain/chat/ChatService.java
> +            AiServerRecommendResponseDto[].class, baseWebClient);
저는 인수가 많으면 이렇게 작성하는데 어떻게 생각하나요?
AiServerRecommendResponseDto[] responseArray = postRequest(
    recommendUri,
    bodyMap,
    AiServerRecommendResponseDto[].class,
    baseWebClient);

2023-06-01 23:45 UTC, min050410 commented on src/main/java/com/recipe/gpt/app/domain/chat/ChatService.java
> +            AiServerRecommendResponseDto[].class, baseWebClient);
구글 코드컨벤션 준수하고 있긴한데 이부분은 이게 더 가독성이 좋은거같애서 수정할게요~~👍

2023-06-02 00:02 UTC, leehj050211 approved these changes
👍

2023-06-02 00:12 UTC, merged