[#1] Feature(Entity): Entity 설계하기
Recipe-GPT/server pull request #6
Opened 2023-05-22 02:08 UTC by min050410

### 작업 사항
- 엔티티 설계

### ERD 참고
![image](https://github.com/Recipe-GPT/server/assets/45661217/8e947003-123b-428c-9eb6-29652c7bbd9e)

2023-05-22 05:34 UTC, leehj050211 requested changes

2023-05-22 05:34 UTC, leehj050211 commented on src/main/java/com/recipe/gpt/app/domain/board/ingredient/Ingredient.java
> +public class Ingredient {
[리뷰 1]
#5 여기에 있는 기능을 구현할 때 이 엔티티하고 이름이 겹칠거 같습니다.
레시피 공유기능에서 사용되는 재료 리스트인 것 같은데 확장성을 위해서 이름을 변경했으면 좋겠네요!

2023-05-22 05:34 UTC, leehj050211 commented on src/main/java/com/recipe/gpt/app/domain/board/ingredient/Ingredient.java
> +    @OneToMany(mappedBy = "board", cascade = CascadeType.PERSIST, orphanRemoval = true)
줄 바꿈도 해주세요!

2023-05-22 05:34 UTC, leehj050211 commented on src/main/java/com/recipe/gpt/app/domain/board/ingredient/IngredientItem.java
> +public class IngredientItem {
리뷰 1 참고

2023-05-22 05:34 UTC, leehj050211 commented on src/main/java/com/recipe/gpt/app/domain/board/seasoning/Seasoning.java
> +public class Seasoning {
리뷰 1 참고

2023-05-22 05:34 UTC, leehj050211 commented on src/main/java/com/recipe/gpt/app/domain/board/seasoning/SeasoningItem.java
> +public class SeasoningItem {
리뷰 1 참고

2023-05-22 05:34 UTC, leehj050211 commented on src/main/java/com/recipe/gpt/app/domain/chat/Chat.java
> +    private Member member;
ChatRoom에도 member_id가 있고 여기도 member_id가 있는데 이렇게 하신 이유가 있나요?
ChatRoom에만 있어도 괜찮을 것 같은데 🤔

2023-05-22 05:34 UTC, leehj050211 commented on src/main/java/com/recipe/gpt/app/domain/member/Member.java
> +    private String password;
OAuth를 사용하는데 password가 있는 이유가 있나요?

2023-05-22 05:34 UTC, leehj050211 commented on src/main/java/com/recipe/gpt/app/domain/board/recipe/Recipe.java
> +public class Recipe {
AI가 생성한 요리 목록, 레시피를 DB에 저장해서 써야하는데 이것도 이름이 겹칠거같아요!
이름을 바꿔주시면 좋을 것 같아요!

2023-05-22 05:34 UTC, leehj050211 commented on src/main/java/com/recipe/gpt/app/web/controller/member/MemberController.java
>  @Tag(name = "인증")
인증 관련 작업을 한다고 태그를 다셨는데 왜 컨트롤러 이름이 Member인가요 🤔

2023-05-22 06:28 UTC, min050410 commented on src/main/java/com/recipe/gpt/app/domain/board/ingredient/Ingredient.java
> +public class Ingredient {
그대로 놔두고 자동완성에서 쓸 엔티티는 데이터니까 ingredient_data는 어떠신지요

2023-05-22 06:30 UTC, min050410 commented on src/main/java/com/recipe/gpt/app/domain/chat/Chat.java
> +    private Member member;
엔티티 내부 메서드로 수정 권한을 얻기 위함입니다.

2023-05-22 06:36 UTC, min050410 commented on src/main/java/com/recipe/gpt/app/domain/member/Member.java
> +    private String password;
검토를 안해봤네요..ㅋㅋ

2023-05-22 06:40 UTC, leehj050211 commented on src/main/java/com/recipe/gpt/app/domain/board/ingredient/Ingredient.java
> +public class Ingredient {
그럼 그렇게 하죠

2023-05-23 00:50 UTC, leehj050211 approved these changes

2023-05-23 06:06 UTC, merged